// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaxf2HGgts-pKvyKA9LW0VrDHWc-v3neU',
    appId: '1:416876427078:web:882b8dea4de57594ed9747',
    messagingSenderId: '416876427078',
    projectId: 'fir-firebase-app-6fa4b',
    authDomain: 'fir-firebase-app-6fa4b.firebaseapp.com',
    storageBucket: 'fir-firebase-app-6fa4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzfdtgcTF3b26DCdzfMlWw5ORlrIIAm_8',
    appId: '1:416876427078:android:798325da77e86fc5ed9747',
    messagingSenderId: '416876427078',
    projectId: 'fir-firebase-app-6fa4b',
    storageBucket: 'fir-firebase-app-6fa4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwE2I_NxuBeYONsRVIe4OCVByXOkaVQu0',
    appId: '1:416876427078:ios:e735fe59997870bced9747',
    messagingSenderId: '416876427078',
    projectId: 'fir-firebase-app-6fa4b',
    storageBucket: 'fir-firebase-app-6fa4b.appspot.com',
    iosBundleId: 'com.example.demoFirbaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwE2I_NxuBeYONsRVIe4OCVByXOkaVQu0',
    appId: '1:416876427078:ios:7f35b0659c9fe283ed9747',
    messagingSenderId: '416876427078',
    projectId: 'fir-firebase-app-6fa4b',
    storageBucket: 'fir-firebase-app-6fa4b.appspot.com',
    iosBundleId: 'com.example.demoFirbaseApp.RunnerTests',
  );
}
